-- MySQL Script generated by MySQL Workbench
-- Tue Dec 24 15:40:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`maintenance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`maintenance` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pompa` VARCHAR(45) NOT NULL,
  `tanggal` DATETIME NULL,
  `jenis_maintenance` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `id_pompa`),
  UNIQUE INDEX `id_pompa_UNIQUE` (`id_pompa` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pompa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pompa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_pompa` VARCHAR(45) NOT NULL,
  `merek_pompa` VARCHAR(200) NOT NULL,
  `daya_pompa` DECIMAL(10) NOT NULL,
  `head_pompa` DECIMAL(10) NOT NULL,
  `dia_pipa` DECIMAL(10) NULL,
  `jenis_pompa` VARCHAR(100) NULL,
  `vendor` VARCHAR(200) NULL,
  `tgl_beli` DATETIME NOT NULL,
  `garansi` DATETIME NULL,
  `status_pompa` VARCHAR(45) NULL,
  PRIMARY KEY (`id`, `id_pompa`),
  UNIQUE INDEX `id_pompa_UNIQUE` (`id_pompa` ASC) VISIBLE,
  CONSTRAINT `maintenance`
    FOREIGN KEY ()
    REFERENCES `mydb`.`maintenance` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pumpit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pumpit` (
  `id` INT GENERATED ALWAYS AS () VIRTUAL,
  `kode_pumpit` VARCHAR(45) NOT NULL,
  `nama_pumpit` VARCHAR(200) BINARY NOT NULL,
  `lokasi_pumpit` VARCHAR(200) NOT NULL,
  `zonasi_pumpit` VARCHAR(45) NULL,
  `dim_p` DECIMAL(10) NULL,
  `dim_l` DECIMAL(10) NULL,
  `dim_t` DECIMAL(10) NULL,
  `jml_pompa` DECIMAL(10) NULL,
  `catchment` VARCHAR(200) NULL,
  `id_pompa` VARCHAR(45) NOT NULL,
  `iblite_ip-addr` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `iblite_ip-addr`),
  UNIQUE INDEX `kode_pumpit_UNIQUE` (`kode_pumpit` ASC) VISIBLE,
  UNIQUE INDEX `id_pompa_UNIQUE` (`id_pompa` ASC) VISIBLE,
  CONSTRAINT `id_pompa`
    FOREIGN KEY (`id_pompa`)
    REFERENCES `mydb`.`pompa` (`id_pompa`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`monitoring_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`monitoring_data` (
  `id` INT GENERATED ALWAYS AS () STORED,
  `id_modul` VARCHAR(45) NOT NULL COMMENT 'password decode',
  `modul_name` VARCHAR(20) NOT NULL COMMENT 'motor Name\n',
  `time` TIMESTAMP(5) NULL,
  `nominal_power` INT(2) UNSIGNED NOT NULL,
  `nomin_current` INT(2) UNSIGNED NOT NULL,
  `timestamp_per` DATETIME NOT NULL,
  `appar_pwr` INT UNSIGNED NOT NULL,
  `motor_state` INT NOT NULL COMMENT 'controller info',
  `usonic_level` INT(2) NOT NULL,
  `run_hours` INT(4) NULL,
  `WrnMaintenAge` DATETIME NULL,
  `Voltage L1-N` DECIMAL(2) UNSIGNED NULL COMMENT 'pump data',
  `Voltage L2-N` DECIMAL(2) UNSIGNED NULL,
  `Voltage L3-N` DECIMAL(2) UNSIGNED NULL,
  `CurrentL1` DECIMAL(2) UNSIGNED NULL,
  `CurrentL2` DECIMAL(2) UNSIGNED NULL,
  `CurrentL3` DECIMAL(2) UNSIGNED NULL,
  PRIMARY KEY (`id_modul`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `ip_address_UNIQUE` (`id_modul` ASC) VISIBLE,
  CONSTRAINT `data_modbus`
    FOREIGN KEY (`id_modul`)
    REFERENCES `mydb`.`pumpit` (`iblite_ip-addr`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(200) NULL,
  `jabatan` VARCHAR(45) NULL,
  `divisi` VARCHAR(45) NULL,
  `role` ENUM('admin', 'teknik', 'viewer') NULL DEFAULT 'viewer',
  `username` VARCHAR(45) NOT NULL,
  `password` INT NULL,
  PRIMARY KEY (`id`, `username`),
  UNIQUE INDEX `iduser_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`data.pasut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`data.pasut` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `time` DATETIME NULL,
  `usonic_lvl` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
