CREATE SEQUENCE POMPATPENUMPANG_SEQ;

CREATE TABLE "POMPA"."POMPA_TPENUMPANG" 
   (	"ID" NUMBER DEFAULT "POMPA"."POMPATPENUMPANG_SEQ"."NEXTVAL" NOT NULL ENABLE, 
	"MOTORNAME" VARCHAR2(15 BYTE) DEFAULT NULL, 
	"PASSDECODE" NUMBER NOT NULL ENABLE, 
	"CONTROLLER_MODE" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"WATERLEVEL" BINARY_DOUBLE NOT NULL ENABLE, 
	"PUMP1_STATUS" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PUMP2_STATUS" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"PUMP3_STATUS" VARCHAR2(10 BYTE) NOT NULL ENABLE, 
	"RUNHOURM1" BINARY_DOUBLE DEFAULT NULL, 
	"RUNHOURM2" BINARY_DOUBLE DEFAULT NULL, 
	"RUNHOURM3" BINARY_DOUBLE DEFAULT NULL, 
	"MAINTENANCE_HOUR" BINARY_DOUBLE DEFAULT NULL, 
	"ENERGYKW" BINARY_DOUBLE DEFAULT NULL, 
	"ENERGYKVA" BINARY_DOUBLE DEFAULT NULL, 
	"APPARENT_POWER" BINARY_DOUBLE DEFAULT NULL, 
	"VOLTAGEL1N" BINARY_DOUBLE DEFAULT NULL, 
	"VOLTAGEL2N" BINARY_DOUBLE DEFAULT NULL, 
	"VOLTAGEL3N" BINARY_DOUBLE DEFAULT NULL, 
	"CURRENTL1" BINARY_DOUBLE DEFAULT NULL, 
	"CURRENTL2" BINARY_DOUBLE DEFAULT NULL, 
	"CURRENTL3" BINARY_DOUBLE DEFAULT NULL, 
	"SET_MAINTAINRUN" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"SET_MAINTAINAGE" VARCHAR2(10 BYTE) DEFAULT NULL, 
	"SET_NOMINAL_POWER" BINARY_DOUBLE DEFAULT NULL, 
	"SET_NOMINAL_CURRENT" BINARY_DOUBLE DEFAULT NULL, 
	"DATETIME" TIMESTAMP (6) DEFAULT (systimestamp) NOT NULL ENABLE
   )
ALTER TABLE "POMPA"."POMPA_TPENUMPANG" ADD CHECK (controller_mode IN ('OFF','MANUAL','AUTO')) ENABLE;
ALTER TABLE "POMPA"."POMPA_TPENUMPANG" ADD CHECK (pump1_status IN ('ON','OFF')) ENABLE;
ALTER TABLE "POMPA"."POMPA_TPENUMPANG" ADD CHECK (pump2_status IN ('ON','OFF')) ENABLE;
ALTER TABLE "POMPA"."POMPA_TPENUMPANG" ADD CHECK (pump3_status IN ('ON','OFF')) ENABLE;
ALTER TABLE "POMPA"."POMPA_TPENUMPANG" ADD PRIMARY KEY ("ID")
  TABLESPACE "POMPA"  ENABLE;
  COMMIT;